var categoryAssociator = {
      shirts: [
        'shirts',
        'shirts-formal-shirts',
        'shirts-business-casual-shirts',
        'shirts-casual-shirts',
        'work-shirts',
        'shirts-evening-shirts',
        'shirts-new-season',
        'shirts-non-iron-shirts',
        'shirts-white-shirt-collection',
        'shirts-blue-collection-shirts',
        'shirts-weave-oxford',
        'shirts-micro-diamond-shirts',
        'shirts-luxury-shirts',
        'linen-collection',
        'tyrwhitt-cool',
        'shirts-short-sleeve-shirts',
        'shirts-classic-fit-shirts',
        'shirts-slim-fit-shirts',
        'shirts-extra-slim-fit-shirts',
        'shirts-super-slim-fit-shirts',
      ],
      polos: ['shirts-polo-shirts'],
      knitwear: [
        'knitwear',
        'knitwear-new-season',
        'knitwear-jumpers',
        'knitwear-cardigans',
        'knitwear-waistcoats',
        'casualwear-merino',
        'knitwear-merino-cashmere',
        'casualwear-pure-cashmere-knitwear',
        'knitwear-zip-neck',
        'knitwear-crew-neck',
        'knitwear-v-neck',
      ],
      ties: [
        'ties',
        'ties-new-season',
        'ties-classic-ties',
        'ties-bow-ties',
        'ties-plain-ties',
        'ties-stripe-ties',
        'ties-floral-ties',
        'ties-slim-ties',
        'ties-animal-ties',
        'ties-grenadine-ties',
        'stain-resistant-ties',
        'ties-luxury-ties',
      ],
      trousers: [
        'trousers',
        'trousers-new-season',
        'trousers-chinos',
        'trousers-5-pocket-trousers',
        'trousers-jumbo-cords',
        'trousers-stretch-textured-trousers',
        'trousers-flannel-trousers',
        'trousers-smart-trousers',
        'trousers-casual-trousers',
        'shorts',
        'trousers-travel-trousers',
      ],
      belts: ['accessories-belts'],
      scarves: ['accessories-scarves'],
      socks: ['accessories-socks'],
      underwear: ['accessories-boxer-shorts'],
    };
